sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t armnpk/reactapp .

script:
  - docker container run -e CI=true armnpk/reactapp npm run test
